require('../../bootstrap');
require('./faqs');
require('./shirt');
require('./forms');
require('./menu');
require('./components');
require('./fingerprint');
require('./spinner');
require('./localization');
